version: '3'
services:
  app:
    container_name: backend_frontend1
    build: ./
    env_file:
      - ./env_ports.env
    links:
      - mongo_db
    ports:
      - 5002:5000  
    depends_on:
      - mongo_db
  
  
  mongo_db:
    container_name: database1964
    image: mongo
