version: '3'
services:
  app:
    container_name: backend_front
    build: ./
    env_file:
      - ./env_ports.env
    links:
      - mongo_db
    ports:
      - 5011:5000  
    depends_on:
      - mongo_db
  
  
  mongo_db:
    container_name: database_db
    image: mongo
